### PR TITLE
Icons appdata

### PR DESCRIPTION
**Pull request by nedrichards**
this should address #3 and goes towards https://github.com/flathub/flathub.org/issues/16

@valentindavid please feel free to modify the OARS ratings from https://hughsie.github.io/oars/generate.html as I think you're a bigger player of the game than I am.

Note: flathub policy on icons has changed. we're OK with using official icons strictly for the purpose of truly and accurately describing the app

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by AsciiWolf** [comment]
It looks like that Albion Online still has the icon missing and still cannot be found in GNOME Software.

**Comment by nedrichards** [comment]
Agreed. This is moderately irritating now.

**Comment by AsciiWolf** [comment]
It looks like that the icons are completely missing in Flathub repo.

**Comment by nedrichards** [comment]
I believe fixed by https://github.com/flathub/com.albiononline.AlbionOnline/commit/0d572015ab425de496612a53caf70ce3cb8b24d8 (and the fixup commit after)

**Comment by AsciiWolf** [comment]
@nedrichards Yep, I can confirm that it is fixed. Thanks!

**Pull request merged**
